### DISCUSSION TITLE
How to avoid CSS leak on react-linear-genome-view ?

### DISCUSSION THREAD

**Discussion by Akusem** [GMOD/jbrowse-components#1800] [Q&A] [answered]
Hi,
Since Jbrowse v1.0.4, the font-family of my page is used by @jbrowse/react-linear-genome-view, e.g.:

![image](https://user-images.githubusercontent.com/24433720/110780112-9d294480-8264-11eb-903a-772c1e8ef6db.png)

Before I was putting the Jbrowse instance inside a `<div>`  with a style defined as `font-family: "roboto, sans-serif"`.
This was sufficient to avoid the `font-family` rule targeting the html and the body tags to interfere with react-linear-genome-view but not anymore.

I imagine this is linked to #1763, which block my so-called 'fix'. Any idea on how I could fix this ?

**Comment by Akusem** [comment, marked as answer]
Finally, I was able to put back the correct font-family by adding the following CSS rule:

```css 
.MuiPaper-root.MuiPaper-elevation1.MuiPaper-rounded {
    font-family: "Roboto", "Helvetica", "Arial", sans-serif;
}
```
