### ISSUE TITLE
Support YAML configs?

### ISSUE THREAD

**Issue by garrettjstevens** [GMOD/jbrowse-components#213]
We're still a ways off from needing to worry about this, but I wanted to get this issue down while I was thinking about it.

Supporting YAML config files (in addition to JSON) might be nice, since YAML and JSON can be inter-converted without loss of data and YAML has some nice features, such as:
- **Multiline strings:** Using the YAML `|-` syntax, a string can span multiple lines, making callback functions defined in the config file easier to read. Example:
```json
{
   "renderers":{
      "PileupRenderer":{
         "type":"PileupRenderer",
         "alignmentColor":"function(feature) {\n  var s = feature.get('strand');\n  return s === '-' || s === -1 ? 'blue': 'red'\n}"
      },
      "SvgFeatureRenderer":{
         "type":"SvgFeatureRenderer",
         "labels":{}
      }
   }
}
```
becomes
```yaml
renderers:
  PileupRenderer:
    type: PileupRenderer
    alignmentColor: |-
      function(feature) {
        var s = feature.get('strand');
        return s === '-' || s === -1 ? 'blue': 'red'
      }
  SvgFeatureRenderer:
    type: SvgFeatureRenderer
    labels: {}
```
- **Comments:** Comments are natively supported in YAML, which makes it easier to e.g. document an example config file
```yaml
renderers:
  # This is valid in YAML
  PileupRenderer:
    type: PileupRenderer
```
